version: '3'

includes:
  helloworld-proto-ts: 
    taskfile: ../helloworld-proto-ts/Taskfile.yml
    dir: ../helloworld-proto-ts
    internal: true

tasks:
  dev:
    cmds:
      - npm run dev

  build:
    sources:
      - ./**/*
      - exclude: ./dist/**/*
    generates:
      - ./dist/**/*
    cmds:
      - task: helloworld-proto-ts:build
      - npm run build

  docker:
    sources:
      - ./**/*
      - exclude: ./dist/**/*
    generates:
      - ./dist/**/*
    cmds:
      - task: build
      - docker build -t helloworld-app .
      
  run:
    cmds:
      - task: docker
      - docker run -p 8080:80 helloworld-app
