version: '3'

tasks:
  dev:
    cmds:
      - npm run dev

  build:
    sources:
      - ./**/*
      - exclude: ./dist/**/*
    generates:
      - ./dist/**/*
    cmds:
      - npm run build

  docker:
    cmds:
      - task: build
      - docker build -t helloworld-app .
      
  run:
    cmds:
      - task: docker
      - docker run -p 8080:80 helloworld-app
