version: 3

includes:
  helloworld-proto-go: 
    taskfile: ../helloworld-proto-go/Taskfile.yml
    dir: ../helloworld-proto-go
    internal: true

tasks:
  dev:
    cmds:
      - air

  build:
    sources:
      - ./**/*
      - exclude: ./dist/**/*
    generates:
      - ./dist/**/*
    cmds:
      - task: helloworld-proto-go:build
      - env GOOS=linux GOARCH=arm64 go build -o dist/helloworld-api ./main.go

  docker:
    sources:
      - ./**/*
      - exclude: ./dist/**/*
    generates:
      - ./dist/**/*
    cmds:
      - task: build
      - docker build -t helloworld-api .
      
  run:
    cmds:
      - task: docker
      - docker run -p 3000:3000 helloworld-api